acme_contacts_homepage:
    pattern:  /contacts
    defaults: { _controller: AcmeContactsBundle:Default:index }
    methods:  [GET]
    
acme_contacts_store:
    pattern:  /contacts
    defaults: { _controller: AcmeContactsBundle:Default:store }
    
acme_contacts_delete:
    pattern:  /contacts/{contactId}
    defaults: { _controller: AcmeContactsBundle:Default:destroy }
    methods:  [DELETE]