acme_contacts_homepage:
    pattern:  /
    defaults: { _controller: AcmeContactsBundle:Default:index }
    
acme_contacts_getall:
    pattern: /contacts
    defaults: { _controller: AcmeContactsBundle:Default:getAll }

